lowerquality/gentle

language_model.py, language_model_transcription.py, standard_kaldi.cc, standard_kaldi.py
Please test this before merging. It works for me but I don't want it to break your stuff.
I'm doing this because I'm experimenting with Bazel files for building standard_kaldi and it builds out of source. It'll also be nice if you don't want to clutter your directory with model files.
=> Remove hard-coded directories

gentle/metasentence.py, tests/metasentence_test.py
also includes a test for the kaldi normalization code
=> handle em dashes in text tokenization

gentle/language_model_transcribe.py
Otherwise there's a file leak that'll crash the server eventually
=> remove gen_model_dir after alignment

gentle/language_model.py, gentle/language_model_transcribe.py
Also remove obsolete TODO about spaces in PROTO_LANGDIR path
=> style: snake case get_language_model

dependencies_osx.sh, dependencies_ubuntu.sh, install.sh, serve.py, setup.py
Some tweaks to the install scripts and server.py to make installation easier
=> Easier server install

dependencies_osx.sh, install.sh
* Fixed some OSX-specific issues
* Stopped building the examples. This speeds things up a helluva lot
=> Build script fixes

standard_kaldi.cc
We might want to make things more flexible with a config file in the future, but this will get rid of all those headaches about rewriting model file paths.
=> obsolete config files; construct recognizers directly in C++

gentle/language_model.py, serve.py, www/index.html, www/status.html
* Decouple saving Status from Twisted
* Change API URLs to better fit REST convention
* General clean-up
=> HTTP API Refactor

gentle/language_model_transcribe.py, gentle/transcription.py, serve.py, tests/transcription_test.py
For performance testing with [sclite](http://www1.icsi.berkeley.edu/Speech/docs/sctk-1.2/sclite.htm#sclite_name_0)
=> Support CTM format

ext/standard_kaldi.cc, gentle/standard_kaldi.py, install_kaldi.sh, tests/e2e_test.py
* Remove unused code
* Add documentation
* Upgrade to C++11
=> clean up standard_kaldi

pylintrc, serve.py, tests/transcriptions_controller_test.py
Let me know if this still works or if I messed up the concurrency model again. I think this approach will be much easier to maintain.
=> TranscriptionController: separate async from sync code

ext/standard_kaldi.cc, gentle/standard_kaldi.py
I'm adding confidences but wanted to clean things up a little first. This puts things into classes which will make it faster to change things later.
=> refactor standard_kaldi

Dockerfile, ext/Makefile, install_models.sh
I forgot to install the Python deps when building the Docker image. This should fix that.
I also added some stuff to make the image smaller and faster.
=> Docker Image Improvements

Dockerfile
15.04 is no longer supported, use current LTS version of Ubuntu
=> Use Ubuntu 16.04 for docker image

gentle/standard_kaldi.py
Hi, thanks for the merge of #99.
But for some reason there was a broken vestigial `import` statement in there, I must have messed something up when I was rebasing my local branches before the push.  Sorry about that.  This fixes that.
=> delete broken vestigial import

gentle/__init__.py, gentle/diff_align.py, gentle/forced_aligner.py, gentle/full_transcriber.py, gentle/multipass.py, gentle/standard_kaldi.py, gentle/transcriber.py, gentle/transcription.py, www/view_alignment.html
More refactoring.  
This adds two new things:
1. Export `gentle.Transcription` and add some useful methods.   (In some client code I cache Transcription results to files and later read them back for further processing.)
2. Make a first-class class for Transcription.Word rather than just using a dict.  I find it clearer to keep track of what's what, especially when there starts getting to be a bunch of nested dicts.  It's available internally as `transcription.Word` and also externally as `gentle.Transcription.Word`
Hope you like these too :)
=> Continuing refactor

gentle/diff_align.py, gentle/full_transcriber.py, gentle/multipass.py, gentle/resources.py, gentle/transcriber.py, gentle/transcription.py, util/paths.py
Some code cleanup.   In particular make sure that Word.end is always defined (to simplify next PR...).
=> Clean up transcription.Word class and its use

ext/Makefile
Linking k3 executables with cuda libraries
=> k3 with cuda

.gitignore, Dockerfile, install_deps.sh
this should also fix install.sh on osx (#182)
=> use python3 setup.py develop instead of pip install

ext/k3.cc
This will probably fix #211. I was having the same issue on my end.
=> Decode last few frames after receiving "get-final"

gentle/resample.py
The FFmpeg suite is sometimes not available (e.g. due to licensing restrictions), and is in general a somewhat heavy dependency for the purpose of (merely) downsampling input audio files. This PR allows Gentle to fall back to using SoX if the `ffmpeg` frontend is not present.
The only downside of using SoX in Gentle is that MP3 (and likely other similarly advanced codecs) is not supported as an input format.
=> Allow the use of SoX if FFmpeg is not available

README.md
Looking at the issues many miss the ./install.sh part
=> Improve guide
